<?php

namespace AppBundle\Repository\VirtualViburnum;


/**
 * CharacterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterTypeRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderAsc() {
		return $this->createQueryBuilder('ct')
		 	->orderBy('ct.characterType','ASC')
			->getQuery()
			->useQueryCache(true)
			->useResultCache(true)
			->getResult();
	}
	
	public function findAllByNotIDs($ids)
	{
	    $qb = $this->createQueryBuilder('ct');
	    return $qb
	    ->where($qb->expr()->notIn('ct.characterTypesId', $ids))
	    ->getQuery()
	    ->getResult();
	}
	
}
