<?php

namespace AppBundle\Repository\VirtualViburnum;


/**
 * CharacterTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterRepository extends \Doctrine\ORM\EntityRepository
{	
	public function findAllByNotIDs($ids)
	{
	    $qb = $this->createQueryBuilder('c');
	    return $qb
	    ->where($qb->expr()->notIn('c.charactersId', $ids))
	    ->getQuery()
	    ->getResult();
	}
	
}
