<?php

namespace AppBundle\Repository\VirtualViburnum;


/**
 * State Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{	
	public function findAllByNotIDs($ids)
	{
	    $qb = $this->createQueryBuilder('s');
	    return $qb
	    ->where($qb->expr()->notIn('s.statesId', $ids))
	    ->getQuery()
	    ->getResult();
	}
	
}
