<?php

namespace AppBundle\Repository\VirtualViburnum;

use AppBundle\Entity\VirtualViburnum\TaxonStatus;

/**
 * TaxonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxaGadmRegionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllByNotIDs($ids)
	{
        $qb = $this->createQueryBuilder('tgr');
		return $qb
		    ->join('tgr.taxon', 't')
			->join('t.taxonStatus', 'ts')
		    ->where('ts.statusName = :status')
			->andWhere($qb->expr()->notIn('tgr.taxaGadmRegionsId', $ids))
			->setParameter('status', TaxonStatus::ACCEPTED)
			->getQuery()
			->getResult();
	}

}
