<?php

namespace AppBundle\Repository\iCViburnum;

/**
 * CharactertypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharactertypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllIDs() {
        return $this
        ->createQueryBuilder("ct")
        ->select("ct.id")
        ->getQuery()
        ->getScalarResult();
    }
}
