<?php

namespace AppBundle\Repository\iCViburnum;

/**
 * CharacterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllIDs() {
        return $this
        ->createQueryBuilder("c")
        ->select("c.id")
        ->getQuery()
        ->getScalarResult();
    }
}
