<?php

namespace AppBundle\Repository\iCViburnum;

use AppBundle\Entity\iCViburnum\Observationstatus;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByUser($user_id) {
        return $this
            ->createQueryBuilder("ob")
            ->select("ob","og","s")
            ->leftJoin("ob.organism", "og")
            ->leftJoin("ob.status", "s")
            ->leftJoin("ob.user", "u")
            ->where("u.id = :user_id")
            ->setParameter("user_id", $user_id)
            ->getQuery();
    }
    
    public function findAllPublished($limit = 25) {
        return $this
            ->createQueryBuilder("ob")
            ->leftJoin("ob.status", "s")
            ->where("s.name = :status")
            ->setParameter("status", Observationstatus::PUBLISHED)
            ->setMaxResults($limit)
		    ->getQuery()
		    ->getResult();
    }
}
