<?php

namespace AppBundle\Repository\iCViburnum;

/**
 * OrganismgadmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganismgadmRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllIDs() {
        return $this
        ->createQueryBuilder("og")
        ->select("og.id")
        ->getQuery()
        ->getScalarResult();
    }
}
