<?php

namespace AppBundle\Repository\iCViburnum;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllIDs() {
        return $this
        ->createQueryBuilder("s")
        ->select(array("s.id", "s.country", "s.stateprovince", "s.districtcountyshire"))
        ->getQuery()
        ->getResult();
    }
}
